QtPath = /home/xiangism/source/qt-4.8.4
QtLiteNote : *.cpp
	g++ -o QtLiteNote *.cpp -I$(QtPath)/include \
		-I$(QtPath)/include/QtCore \
		-I$(QtPath)/include/QtGui \
		-I$(QtPath)/include/QtWebKit \
		-L$(QtPath)/lib \
		-lQtGui -lQtCore -lQtWebKit
